from enum import Enum

class Degree(Enum):
    BACHELOR = "Bachelor"
    MASTER = "Master"
    DOCTOR = "Doctor"

class FieldOfStudy(Enum):
    COMPUTER_SCIENCE_AND_ENGINEERING = "Computer Science & Engineering"

class Technology(Enum):
    PYTHON = "Python"
    JAVA = "Java"
    JAVASCRIPT = "JavaScript"
    TYPESCRIPT = "TypeScript"
    GOLANG = "Golang"
    REACT = "React"
    NODE_JS = "Node.js"
    EXPRESS = "Express"
    REACT_JS = "React.js"
    DJANGO = "Django"
    EXPRESS_JS = "Express.js"
    ANGULAR = "Angular"
    VUE = "Vue"
    NEXT_JS = "Next.js"
    TAILWIND = "Tailwind"
    POSTGRESQL = "PostgreSQL"
    MYSQL = "MySQL"
    MONGODB = "MongoDB"
    CLICK_HOUSE = "Click-House"
    REDIS = "Redis"
    AWS = "AWS"
    DOCKER = "Docker"
    GITHUB_ACTIONS = "GitHub Actions"
    CI_CD = "CI/CD"
    KAFKA = "Kafka"
    RABBITMQ = "RabbitMQ"
    JEST = "Jest"
    POSTMAN = "Postman"
    SWAGGER = "Swagger"
    GIT = "Git"
    JIRA = "JIRA"
    VS_CODE = "VS Code"
    CURSOR = "Cursor"